#!/bin/sh

LIBS="zeda zm zeo dzco roki zx11 liw roki-gl"

for lib in ${LIBS}
do
  if [ -d ${lib} ]; then
    cd ${lib}
    sudo make uninstall
    cd -
  else
    echo "cannot find directory" ${lib}
    exit 1
  fi
done

echo "uninstallation completed."

exit 0
