#!/bin/sh

SUDO=sudo

LIBS="roki-gl liw zx11 roki zeo dzco neuz zm zeda"

# install libraries from .deb packages
for lib in ${LIBS}
do
  # dpkg
  echo "uninstalling" ${lib} "..."
  ${SUDO} dpkg --purge ${lib}
done

echo "completed."

exit 0
