#!/bin/sh

LIBS="zeda zm neuz dzco zeo roki zx11 liw roki-gl"

# compile
compile(){
  if [ -d ${lib} ]; then
    cd ${lib}
    make clean
    make && make install || ( echo  "failed to compile " ${lib}; exit 1 )
    make deb && mv *.deb ..
    cd -
  else
    echo "cannot find directory" ${lib}
    exit 1
  fi
}

# makeclean
makeclean(){
  if [ -d ${lib} ]; then
    cd ${lib}
    make clean
    cd -
  else
    echo "cannot find directory" ${lib}
    exit 1
  fi
}

case $1 in
  install)
    for lib in ${LIBS}
    do
      compile
    done
  ;;
  clean)
    for lib in $LIBS
    do
      makeclean
    done
  ;;
  *)
    for lib in ${LIBS}
    do
      compile
    done
  ;;
esac

exit 0
