#!/bin/sh

### Edit the following path for your preference.
PREFIX=

if [ -z ${PREFIX} ]; then
  PREFIX=`readlink -f $1`
fi

# check if installer has to be run by the superuser

SUDO=
if [ `ls -ld ${PREFIX} | cut -d " " -f 3` != `whoami` ]; then
  SUDO="sudo"
fi

echo "installing libraries and tools under" ${PREFIX} "..."

BINDIR=${PREFIX}/bin
INCDIR=${PREFIX}/include
LIBDIR=${PREFIX}/lib

LIBS="zeda zm neuz dzco zeo roki zx11 liw roki-gl"

# make directories

for dir in ${BINDIR} ${INCDIR} ${LIBDIR}
do
  echo "making directory" ${dir} "..."
  ${SUDO} mkdir -p ${dir}
  if [ ! -d ${dir} ]; then
    echo "cannot make" ${dir};
    exit 1;
  fi
done

# check if path is valid

if [ -z `echo ${PATH} | grep ${BINDIR}` ]; then
  echo "Add ${BINDIR} into your PATH by"
  echo "  export PATH=${BINDIR}:\$PATH"
  echo "for Bourne shell family (bash, zsh, ksh, etc.), or by"
  echo "  set path = ( ${BINDIR} \$path )"
  echo "for C shell family (csh, tcsh etc.)."
  exit 0
fi
echo ${BINDIR} "... valid path."

# check if libraries are visible from linker

if [ -z `echo $LD_LIBRARY_PATH | grep $LIBDIR` ]; then
  echo "Add ${LIBDIR} into your LD_LIBRARY_PATH by"
  echo "  export LD_LIBRARY_PATH=${LIBDIR}:\$LD_LIBRARY_PATH"
  echo "for Bourne shell family (bash, zsh, ksh, etc.), or by"
  echo "  setenv LD_LIBRARY_PATH ${LIBDIR}:\$LD_LIBRARY_PATH"
  echo "for C shell family (csh, tcsh etc.)."
  exit 0
fi
echo ${LIBDIR} "in LD_LIBRARY_PATH."

echo "installing required packages..."

# get apt packages
# (for download & compilation)
sudo apt install git wget unzip rename make gcc
# (for X11 & GL)
sudo apt install xorg-dev libtiff-dev libjpeg-dev freeglut3-dev

# download archive files from GitHub, compile, and install libraries
for lib in ${LIBS}
do
  # download & unarchive
  if [ ! -d ${lib} ]; then
    echo "downloading" ${lib} "..."
    wget https://github.com/zhidao/${lib}/archive/master.zip
    echo "unarchiving" ${lib} "..."
    unzip master.zip
    rm master.zip
    rename 's/-master//' *-master
  fi
  # compile & install
  echo "compiling" ${lib} "..."
  if [ -d ${lib} ]; then
    cd ${lib}
    if [ -n "${PREFIX}" ]; then
	rm config;
	cat config.org | sed -e "/^PREFIX/c\PREFIX=${PREFIX}" > config;
    fi
    if [ ! -f config ]; then
	cp config.org config;
    fi
    make clean
    ${SUDO} make && ${SUDO} make install || ( echo  "failed to compile " ${lib}; exit 1 )
    cd -
  else
    echo "cannot find directory" ${lib}
    exit 1
  fi
done

echo "completed."

exit 0
