#!/bin/sh
echo "installing required packages..."
## get apt packages
### (for download & compilation)
sudo apt install git wget unzip rename make gcc fakeroot pkg-config
### (for ZEDA & X11 & OpenGL)
sudo apt install libxml2-dev liblzf-dev xorg-dev libxft-dev libfreetype-dev libtiff-dev libjpeg-dev libmagickwand-dev freeglut3-dev libglew-dev libglfw3-dev
