#!/bin/sh

echo "uninstall libraries..."

# read variables in config file.
. ./config

# uninstall Debian packages
if [ "$1" = "deb" ]; then
  sudo dpkg --purge ${LIBS}
  echo "completed."
  exit 0
fi

if [ -z ${PREFIX} ]; then
  PREFIX=${HOME}/usr
fi

## check if installer has to be run by the superuser
SUDO=
if [ `ls -ld ${PREFIX} | cut -d " " -f 3` != `whoami` ]; then
  SUDO="sudo"
fi

# uninstall libraries in the reverse order.
LIBS_REV=
for lib in ${LIBS}
do
    LIBS_REV="${lib} ${LIBS_REV}"
done

for lib in ${LIBS_REV}
do
  if [ -d ${lib} ]; then
    cd ${lib}; ${SUDO} make uninstall; cd -
  else
    echo "cannot find directory" ${lib}
  fi
done

echo "completed."

exit 0
