#!/bin/sh

# read variables in config file.
. ./config

cc=
std=

# compile
compile(){
  if [ -d ${lib} ]; then
    cd ${lib}
    make clean
    make CC=${cc} STD=${std} && make install || ( echo  "failed to compile " ${lib}; exit 1 )
    cd -
  else
    echo "cannot find directory" ${lib}
    exit 1
  fi
}

# makedeb
makedeb(){
  if [ -d ${lib} ]; then
    cd ${lib}
    make deb && mv *.deb ../deb
    cd -
  else
    echo "cannot find directory" ${lib}
    exit 1
  fi
}

# makeclean
makeclean(){
  if [ -d ${lib} ]; then
    cd ${lib}
    make clean
    cd -
  else
    echo "cannot find directory" ${lib}
    exit 1
  fi
}

# git pull
dopull(){
  if [ -d ${lib} ]; then
    cd ${lib}
    git pull
    cd -
  else
    echo "cannot find directory" ${lib}
    exit 1
  fi
}

case $1 in
  deb)
    rm deb/*.deb
    for lib in ${LIBS}
    do
      makedeb
    done
    ;;
  clean)
    for lib in ${LIBS}
    do
      makeclean
    done
    ;;
  pull)
    for lib in ${LIBS}
    do
      dopull
    done
    ;;
  cpplib)
    cc=g++
    std=c++17
    for lib in ${LIBS}
    do
      compile
    done
    ;;
  *)
    cc=gcc
    std=c89
    for lib in ${LIBS}
    do
      compile
    done
    ;;
esac

exit 0
